// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_row_z
NumericMatrix fast_row_z(NumericMatrix x);
RcppExport SEXP _OmniOmicsR_fast_row_z(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_row_z(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_col_z
NumericMatrix fast_col_z(NumericMatrix x);
RcppExport SEXP _OmniOmicsR_fast_col_z(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_col_z(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OmniOmicsR_fast_row_z", (DL_FUNC) &_OmniOmicsR_fast_row_z, 1},
    {"_OmniOmicsR_fast_col_z", (DL_FUNC) &_OmniOmicsR_fast_col_z, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_OmniOmicsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
