# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_row_z <- function(x) {
    .Call(`_OmniOmicsR_fast_row_z`, x)
}

fast_col_z <- function(x) {
    .Call(`_OmniOmicsR_fast_col_z`, x)
}

